services:
  - type: web
    name: AKshare-streamlit
    env: python
    branch: main
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.headless true
    envVars:
      - key: SOME_SECRET
        value: "your_secret_value"
